cargo-features = ["edition2024"]

[package]
name = "jetdbg"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
inkwell = { version = "0.4.0", features = ["llvm18-0"], git = "https://github.com/TheDan64/inkwell.git" }
log = "0.4"
simple_logger = "5.0.0"
jet = { path = "../../crates/jet" }
