cargo-features = ["edition2024"]

[package]
name = "jet_runtime"

[lib]
name = "jet_runtime"
crate-type = ["dylib"]

[dependencies]
hex = "0.4.3"
inkwell = { workspace = true, rev = "6c0fb56b3554e939f9ca61b465043d6a84fb7b95", features = ["llvm18-0", "llvm-sys-180"], git = "https://github.com/TheDan64/inkwell.git" }
